### ISSUE TITLE
Startup fails with "unshare: mount ... on ... failed: Invalid argument"

### ISSUE THREAD

**Issue by nzbr** [nix-community/NixOS-WSL#292]
## Bug description
When trying to start NixOS-WSL, it fails with an error like
```
[ERROR] systemd startup failed!
[ERROR] stderr:
unshare: mount /proc/455/ns/mnt on /run/nixos-wsl/ns/mount failed: Invalid argument
+ grep -q binfmt_misc /proc/filesystems
+ mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
+ exec systemd
[ERROR] stdout:
```

## To Reproduce
Update WSL to the new 2.0.0.0 release and try to start NixOS using syschdemd

## Resolution
Run the following commands to update to the latest NixOS-WSL version and switch to native systemd:

```powershell
wsl -d NixOS -e /nix/var/nix/profiles/system/sw/bin/bash
```

This shoudl give you a root shell in the NixOS distro. From there run:

```sh
/nix/var/nix/profiles/system/activate
. /etc/set-environment
```

Now update NixOS-WSL by running

```sh
rm -rf /etc/nixos/nixos-wsl
curl -L https://api.github.com/repos/nix-community/nixos-wsl/tarball/main | tar -xzv
mv nix-community-NixOS-WSL-* /etc/nixos/nixos-wsl
nix-channel --add https://nixos.org/channels/nixos-23.05 nixos
nix-channel --update
```

Use an Editor (nano/vim) to edit `/etc/nixos/configuration.nix` and set the option
```nix
    wsl.nativeSystemd = true;
```

Save the file and run (this will print some errors, but that's fine)

```
nixos-rebuild switch
```

After that, exit back to your windows shell and run

```
wsl -t NixOS
wsl -d NixOS
```

If this gives you a shell as the default user, everything should be working again

**Comment by fc1943s** [comment]
almost! error at the end of rebuild: (tried with an old installation and a fresh install)
![image](https://github.com/nix-community/NixOS-WSL/assets/688618/bc299176-2663-4bdc-9a89-fba6b511651b)

**Comment by K900** [comment]
That's a warning, not an error.

**Comment by K900** [comment]
The actual issue is fixed on main, so I'll close the issue, but leave it pinned for visibility.

**Comment by nzbr** [comment]
Wouldn't it still fail with syschdemd? I'd not say it's fixed but rather no longer relevant (therefore the wontfix label)

**Comment by K900** [comment]
I fixed it on main.
